package com.tripsyncai.service;

import com.tripsyncai.dto.CreateInvitationRequest;
import com.tripsyncai.dto.InvitationResponse;
import com.tripsyncai.dto.JoinTripRequest;
import com.tripsyncai.dto.TripJoinPreviewResponse;
import com.tripsyncai.entity.*;
import com.tripsyncai.exception.ResourceNotFoundException;
import com.tripsyncai.repository.TripInvitationRepository;
import com.tripsyncai.repository.TripMemberRepository;
import com.tripsyncai.repository.TripRepository;
import com.tripsyncai.util.TokenUtils;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.stream.Collectors;

@Slf4j
@Service
@RequiredArgsConstructor
public class TripInvitationService {

    private final TripRepository tripRepository;
    private final TripInvitationRepository tripInvitationRepository;
    private final TripMemberRepository tripMemberRepository;
    private final TripAuthorizationService tripAuthorizationService;
    private final SecurityAuditService securityAuditService;

    @Transactional
    public InvitationResponse createInvitation(Long tripId, CreateInvitationRequest request, User caller) {
        tripAuthorizationService.verifyRole(tripId, caller, TripRole.ORGANIZER);

        Trip trip = tripRepository.findById(tripId)
                .orElseThrow(() -> new ResourceNotFoundException("Trip not found with id: " + tripId));

        String rawToken = TokenUtils.generateSecureToken(32);
        String tokenHash = TokenUtils.hashToken(rawToken);
        LocalDateTime expiresAt = LocalDateTime.now().plusDays(7);

        TripInvitation invitation = TripInvitation.builder()
                .trip(trip)
                .inviter(caller)
                .tokenHash(tokenHash)
                .recipientEmail(request != null ? request.getRecipientEmail() : null)
                .expiresAt(expiresAt)
                .status("ACTIVE")
                .build();

        TripInvitation saved = tripInvitationRepository.save(invitation);

        securityAuditService.recordEvent(
                tripId,
                caller.getId(),
                "INVITATION_CREATED",
                String.format("Trip invitation link generated by @%s", caller.getUsername()),
                null
        );

        return InvitationResponse.builder()
                .id(saved.getId())
                .tripId(trip.getId())
                .tripName(trip.getName())
                .inviterUsername(caller.getUsername())
                .inviteToken(rawToken)
                .joinUrl("/trips/join?token=" + rawToken)
                .expiresAt(expiresAt)
                .status(saved.getStatus())
                .build();
    }

    @Transactional(readOnly = true)
    public TripJoinPreviewResponse previewInvitation(String rawToken) {
        if (rawToken == null || rawToken.isBlank()) {
            throw new IllegalArgumentException("Invitation token cannot be empty");
        }

        String tokenHash = TokenUtils.hashToken(rawToken.trim());
        TripInvitation invitation = tripInvitationRepository.findByTokenHashAndStatus(tokenHash, "ACTIVE")
                .orElseThrow(() -> new ResourceNotFoundException("Invalid or expired invitation link"));

        if (invitation.getExpiresAt().isBefore(LocalDateTime.now())) {
            throw new IllegalArgumentException("This invitation link has expired");
        }

        Trip trip = invitation.getTrip();
        List<TripMember> members = tripMemberRepository.findByTripId(trip.getId());
        List<String> memberNames = members.stream()
                .map(TripMember::getUser)
                .filter(Objects::nonNull)
                .map(u -> u.getFullName() != null ? u.getFullName() : u.getUsername())
                .collect(Collectors.toList());

        User inviter = invitation.getInviter();

        return TripJoinPreviewResponse.builder()
                .tripId(trip.getId())
                .tripName(trip.getName())
                .description(trip.getDescription())
                .startDate(trip.getStartDate())
                .endDate(trip.getEndDate())
                .baseCurrency(trip.getBaseCurrency())
                .inviterUsername(inviter != null ? inviter.getUsername() : "Trip Organizer")
                .inviterFullName(inviter != null ? inviter.getFullName() : null)
                .memberCount(members.size())
                .memberNames(memberNames)
                .valid(true)
                .build();
    }

    @Transactional
    public Map<String, Object> joinTrip(JoinTripRequest request, User user) {
        String rawToken = request != null && request.getToken() != null ? request.getToken().trim() : "";
        if (rawToken.isBlank()) {
            throw new IllegalArgumentException("Invitation token is required");
        }

        String tokenHash = TokenUtils.hashToken(rawToken);
        TripInvitation invitation = tripInvitationRepository.findByTokenHashAndStatus(tokenHash, "ACTIVE")
                .orElseThrow(() -> new ResourceNotFoundException("Invalid or expired invitation link"));

        if (invitation.getExpiresAt().isBefore(LocalDateTime.now())) {
            throw new IllegalArgumentException("This invitation link has expired");
        }

        Trip trip = invitation.getTrip();

        // Check if user is already a member
        if (tripMemberRepository.existsByTripIdAndUserId(trip.getId(), user.getId())) {
            return Map.of(
                    "message", "You are already a member of this trip!",
                    "tripId", trip.getId(),
                    "alreadyMember", true
            );
        }

        // Add user to trip as MEMBER
        TripMember newMember = TripMember.builder()
                .trip(trip)
                .user(user)
                .role(TripRole.MEMBER)
                .joinedAt(LocalDateTime.now())
                .build();
        tripMemberRepository.save(newMember);

        // If this was an email-targeted invite, mark it as USED
        if (invitation.getRecipientEmail() != null && !invitation.getRecipientEmail().isBlank()) {
            invitation.setStatus("USED");
            invitation.setUsedAt(LocalDateTime.now());
            tripInvitationRepository.save(invitation);
        }

        securityAuditService.recordEvent(
                trip.getId(),
                user.getId(),
                "MEMBER_JOINED_VIA_INVITATION",
                String.format("@%s joined the trip via invitation", user.getUsername()),
                null
        );

        return Map.of(
                "message", "Successfully joined the trip!",
                "tripId", trip.getId(),
                "alreadyMember", false
        );
    }
}
